log:
  level: info

db:
  type: sqlite

worker:
  mode: regular
  count: 1

  waitMainNodeReady:
    enabled: true

  livenessProbe:
    initialDelaySeconds: 60
    periodSeconds: 20
    failureThreshold: 5

  readinessProbe:
    initialDelaySeconds: 60
    periodSeconds: 20
    failureThreshold: 5

webhook:
  mode: regular
  count: 1

  waitMainNodeReady:
    enabled: true

  livenessProbe:
    initialDelaySeconds: 60
    periodSeconds: 20
    failureThreshold: 5

  readinessProbe:
    initialDelaySeconds: 60
    periodSeconds: 20
    failureThreshold: 5

nodes:
  python:
    enabled: true
    builtin:
      modules:
        - "*"
    external:
      packages:
        - numpy
        - pandas

taskRunners:
  mode: external
  external:
    image:
      repository: n8nio/runners
      pullPolicy: IfNotPresent
      tag: ""
    resources:
      requests:
        cpu: 100m
        memory: 64Mi
      limits:
        cpu: 500m
        memory: 256Mi
